# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FamilyConnectionTree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Content')),
                ('img', models.ImageField(default='../static/css/images/bg.jpg', upload_to='pic_folder/', verbose_name='Image')),
                ('post_type', models.IntegerField(choices=[(1, 'News'), (2, 'Memories'), (3, 'Facts')], default=1, verbose_name='Post Type')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyConnectionTree.Family')),
            ],
        ),
    ]
