# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyConnectionTree', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='family',
        ),
    ]
