# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyConnectionTree', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FamilyConnectionTree.Family'),
        ),
    ]
